import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, BookOpen, Calendar, Check, Clock3, LineChart, Sparkles, Target, TrendingUp, Zap } from "lucide-react";
import { ProtectedRoute, useAuth } from "@/lib/auth";
import { DashboardShell } from "@/components/layout/DashboardShell";
import { attemptsRepo, computeStats, type ExamAttempt } from "@/lib/domain";
import { MILLIY_SUBJECTS } from "@/lib/milliy";
import { getLatestStudyPlan, getStudentProfile, syncPendingOnboarding } from "@/lib/learning";

export const Route = createFileRoute("/dashboard")({ component: Dashboard, head: () => ({ meta: [{ title: "Bosh sahifa — INTIL" }] }) });
function Dashboard() { return <ProtectedRoute><DashboardContent /></ProtectedRoute>; }
function fmtDate(iso?: string | null) { if (!iso) return ""; try { return new Date(iso).toLocaleDateString("uz-UZ", { day: "2-digit", month: "long", year: "numeric" }); } catch { return ""; } }
function computeStreak(attempts: ExamAttempt[]) { if (!attempts.length) return 0; const key=(d:Date)=>d.toISOString().slice(0,10); const days=new Set(attempts.map(a=>key(new Date(a.finishedAt)))); let d=new Date(); if(!days.has(key(d))){d.setDate(d.getDate()-1);if(!days.has(key(d)))return 0;} let n=0;while(days.has(key(d))){n++;d.setDate(d.getDate()-1);}return n; }
function Card({children,className=""}:{children:React.ReactNode;className?:string}){return <div className={`rounded-[24px] border border-edge bg-white ${className}`}>{children}</div>}
function IconPlate({icon:Icon}:{icon:React.ComponentType<{className?:string;strokeWidth?:number}>}){return <span className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-[#F7F1E5]"><Icon className="h-[18px] w-[18px] text-brass" strokeWidth={1.6}/></span>}
type AiTask={subject?:string;topic?:string;minutes?:number;task?:string}; type AiDay={day?:number;focus?:string;total_minutes?:number;tasks?:AiTask[]}; type AiPlan={title?:string;summary?:string;days?:AiDay[];rules?:string[]};
function DashboardContent(){
 const {user}=useAuth(); const [attempts,setAttempts]=useState<ExamAttempt[]|null>(null); const [plan,setPlan]=useState<AiPlan|null>(null); const [profile,setProfile]=useState<any>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!user?.id)return;let cancelled=false;(async()=>{try{await syncPendingOnboarding(user.id);const [p,sp]=await Promise.all([getLatestStudyPlan(user.id),getStudentProfile(user.id)]);if(!cancelled){setPlan(p?.plan??null);setProfile(sp);}}catch(e){console.error("[INTIL] dashboard load",e)}finally{if(!cancelled)setLoading(false)}})();setAttempts(attemptsRepo.list(user.id));return()=>{cancelled=true}},[user?.id]);
 const list=attempts??[]; const stats=useMemo(()=>attempts?computeStats(list):null,[attempts]); const streak=useMemo(()=>computeStreak(list),[attempts]); const first=plan?.days?.[0];
 const daysLeft=profile?.exam_date?Math.max(0,Math.ceil((new Date(`${profile.exam_date}T23:59:59`).getTime()-Date.now())/86400000)):null; const minutes=profile?.daily_study_minutes??first?.total_minutes??null;
 const subjectNames=(profile?.selected_subjects??[]).map((s:string)=>MILLIY_SUBJECTS[s]?.name??({math:"Matematika",physics:"Fizika",history:"Tarix",uzbek:"Ona tili",biology:"Biologiya",chemistry:"Kimyo",english:"Ingliz tili"}[s]??s));
 const weak=profile?.weak_points??{}; const weakList=Object.entries(weak).flatMap(([s,topics])=>(topics as string[]).map(t=>({subject:MILLIY_SUBJECTS[s]?.name??({math:"Matematika",physics:"Fizika",history:"Tarix",uzbek:"Ona tili",biology:"Biologiya",chemistry:"Kimyo",english:"Ingliz tili"}[s]??s),topic:t}))).slice(0,6);
 return <DashboardShell title="Bosh sahifa" subtitle={`Xush kelibsiz, ${user?.fullName??"talaba"}`} streakDays={streak}>
  <section className="relative overflow-hidden rounded-[28px] bg-[#171717] px-6 py-7 text-white sm:px-8 sm:py-8"><div className="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-[#B9975B]/15 blur-3xl"/><div className="relative grid gap-7 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex items-center gap-2 text-[12px] font-semibold uppercase tracking-[.18em] text-[#D8B878]"><Sparkles className="h-4 w-4"/> INTIL AI</div><h1 className="mt-3 max-w-2xl text-3xl font-semibold tracking-[-.03em] sm:text-4xl">Sizning tayyorgarligingiz. <span className="text-[#D8B878]">Sizga moslashtirilgan.</span></h1><p className="mt-3 max-w-xl text-[14px] leading-6 text-white/60">{loading?"Shaxsiy ma'lumotlaringiz tahlil qilinmoqda…":plan?.summary??"Avval onboardingni yakunlang. INTIL fanlaringiz va maqsadingiz asosida shaxsiy Study Plan yaratadi."}</p></div><div className="grid grid-cols-2 gap-2 sm:gap-3"><div className="min-w-[110px] rounded-2xl border border-white/10 bg-white/[.05] px-4 py-4"><Clock3 className="h-4 w-4 text-[#D8B878]"/><p className="mt-3 text-2xl font-semibold">{daysLeft !== null ? daysLeft : "Sozlash"}</p><p className="mt-1 text-[11px] text-white/50">{daysLeft !== null ? "kun qoldi" : "imtihon sanasi"}</p></div><div className="min-w-[110px] rounded-2xl border border-white/10 bg-white/[.05] px-4 py-4"><Target className="h-4 w-4 text-[#D8B878]"/><p className="mt-3 text-2xl font-semibold">{profile?.target_score ?? "Sozlash"}</p><p className="mt-1 text-[11px] text-white/50">{profile?.target_score ? "target ball" : "maqsad ball"}</p></div></div></div></section>
  <div className="mt-5 grid gap-4 sm:grid-cols-3"><Card className="p-5"><div className="flex items-center justify-between"><span className="text-[12px] font-semibold uppercase tracking-[.12em] text-ink-mute">Kunlik vaqt</span><Clock3 className="h-4 w-4 text-brass"/></div><p className="mt-3 text-2xl font-semibold text-ink-strong">{minutes ? `${minutes} daq.` : "Onboarding"}</p></Card><Card className="p-5"><div className="flex items-center justify-between"><span className="text-[12px] font-semibold uppercase tracking-[.12em] text-ink-mute">Fanlar</span><BookOpen className="h-4 w-4 text-brass"/></div><p className="mt-3 text-2xl font-semibold text-ink-strong">{subjectNames.length ? subjectNames.length : "Tanlanmagan"}</p></Card><Card className="p-5"><div className="flex items-center justify-between"><span className="text-[12px] font-semibold uppercase tracking-[.12em] text-ink-mute">Streak</span><Zap className="h-4 w-4 text-brass"/></div><p className="mt-3 text-2xl font-semibold text-ink-strong">{streak} <span className="text-sm font-normal text-ink-mute">kun</span></p></Card></div>
  <div className="mt-5 grid gap-5 lg:grid-cols-[1.4fr_.8fr]"><Card className="p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div className="flex gap-3.5"><IconPlate icon={Sparkles}/><div><p className="text-[12px] font-semibold uppercase tracking-[.12em] text-brass">AI reja</p><h2 className="mt-1 text-xl font-semibold text-ink-strong">Bugungi fokus</h2></div></div>{first?.total_minutes?<span className="rounded-full bg-[#F7F1E5] px-3 py-1.5 text-[12px] font-semibold text-ink-strong">{first.total_minutes} daqiqa</span>:null}</div>{first?<><div className="mt-5 rounded-2xl bg-[#FAF8F3] p-4"><p className="text-[16px] font-semibold text-ink-strong">{first.focus??"Bugungi mashg'ulot"}</p><div className="mt-4 space-y-2">{(first.tasks??[]).slice(0,5).map((t,i)=><div key={i} className="flex items-start gap-3 rounded-xl bg-white px-3.5 py-3"><span className="mt-1 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-[#F7F1E5]"><Check className="h-3 w-3 text-brass"/></span><div className="min-w-0 flex-1"><p className="text-[13px] font-semibold text-ink-strong">{t.subject}{t.topic?` · ${t.topic}`:""}</p><p className="mt-0.5 text-[13px] text-ink-mute">{t.task}</p></div>{t.minutes?<span className="text-[12px] text-ink-mute">{t.minutes} daq.</span>:null}</div>)}</div></div><div className="mt-4 flex flex-wrap gap-2"><Link to="/study-plan" className="inline-flex h-11 items-center gap-2 rounded-xl border border-edge bg-white px-5 text-[13px] font-semibold text-ink-strong">To‘liq Study Plan <ArrowRight className="h-4 w-4"/></Link><Link to="/milliy-sertifikat" className="inline-flex h-11 items-center gap-2 rounded-xl bg-deep px-5 text-[13px] font-semibold text-white">Bugungi mashqni boshlash <ArrowRight className="h-4 w-4"/></Link></div></>:<div className="mt-5 rounded-2xl bg-[#FAF8F3] p-5"><p className="text-[14px] leading-6 text-ink-mute">Shaxsiy reja hali yaratilmagan. Bu bo‘sh holat emas — keyingi qadam onboarding orqali maqsadingizni belgilash.</p><Link to="/onboarding" className="mt-4 inline-flex h-11 items-center gap-2 rounded-xl bg-deep px-5 text-[13px] font-semibold text-white">Rejamni yaratish <Sparkles className="h-4 w-4"/></Link></div>}</Card>
  <Card className="p-5 sm:p-6"><div className="flex items-center gap-3"><IconPlate icon={Target}/><div><p className="text-[12px] font-semibold uppercase tracking-[.12em] text-brass">AI tahlili</p><h2 className="mt-1 text-lg font-semibold text-ink-strong">Kuchsiz nuqtalar</h2></div></div>{weakList.length?<div className="mt-5 space-y-3">{weakList.map((w,i)=><div key={i} className="rounded-xl border border-edge px-3.5 py-3"><p className="text-[11px] font-semibold uppercase tracking-[.08em] text-ink-mute">{w.subject}</p><p className="mt-1 text-[13px] font-semibold text-ink-strong">{w.topic}</p></div>)}</div>:<p className="mt-5 text-[14px] leading-6 text-ink-mute">Imtihonlarni ishlaganingiz sari INTIL qaysi mavzularda ko‘proq xato qilayotganingizni aniqlaydi.</p>}</Card></div>
  <div className="mt-5 grid gap-5 lg:grid-cols-2"><Card className="p-5 sm:p-6"><div className="flex items-center gap-3"><IconPlate icon={LineChart}/><h3 className="text-[17px] font-semibold text-ink-strong">Natijalar</h3></div>{stats&&list.length?<div className="mt-5 grid grid-cols-3 gap-3">{[["Imtihonlar",stats.totalTests],["O‘rtacha",`${stats.averagePercent}%`],["Eng yuqori",`${stats.bestPercent}%`]].map(([l,v])=><div key={l} className="rounded-2xl bg-[#FAF8F3] p-4"><p className="text-[11px] uppercase tracking-[.08em] text-ink-mute">{l}</p><p className="mt-2 text-xl font-semibold text-ink-strong">{v}</p></div>)}</div>:<p className="mt-4 text-[14px] leading-6 text-ink-mute">Birinchi imtihoningiz tugagach, natija va progress shu yerda ko‘rinadi.</p>}</Card><Card className="p-5 sm:p-6"><div className="flex items-center gap-3"><IconPlate icon={TrendingUp}/><h3 className="text-[17px] font-semibold text-ink-strong">Tayyorgarlik yo‘nalishi</h3></div><div className="mt-5 flex flex-wrap gap-2">{subjectNames.length?subjectNames.map(s=><span key={s} className="rounded-full border border-edge bg-[#FAF8F3] px-3 py-2 text-[12px] font-medium text-ink-strong">{s}</span>):<Link to="/onboarding" className="text-sm font-semibold text-ink-strong">Fanlarni tanlash →</Link>}</div><div className="mt-5 rounded-2xl bg-deep p-4 text-white"><p className="text-[13px] font-semibold">INTIL siz bilan birga moslashadi.</p><p className="mt-1 text-[12px] leading-5 text-white/55">Har bir yechilgan savol keyingi reja va mavzu ustuvorligiga ta’sir qiladi.</p></div></Card></div>
  <Card className="mt-5 p-5 sm:p-6"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><IconPlate icon={Calendar}/><div><h3 className="text-[17px] font-semibold text-ink-strong">Oxirgi imtihon</h3><p className="text-[13px] text-ink-mute">Natijalar va davomiy progress</p></div></div><Link to="/study-plan" className="inline-flex items-center gap-1.5 text-[13px] font-semibold text-ink-strong">Study Plan <ArrowRight className="h-4 w-4"/></Link></div>{list.length?<div className="mt-4 border-t border-edge pt-4"><p className="text-[14px] font-medium text-ink-strong">{list[0].examTitle}</p><p className="mt-1 text-[13px] text-ink-mute">{fmtDate(list[0].finishedAt)} · {list[0].correct}/{list[0].total} to‘g‘ri</p></div>:<p className="mt-4 border-t border-edge pt-4 text-[14px] text-ink-mute">Hozircha yakunlangan imtihon yo‘q.</p>}</Card>
 </DashboardShell>
}
