/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DtmRouteImport } from './routes/dtm'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MateriallarRouteImport } from './routes/materiallar'
import { Route as NatijalarRouteImport } from './routes/natijalar'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudyPlanRouteImport } from './routes/study-plan'
import { Route as TestlarRouteImport } from './routes/testlar'
import { Route as AdminYozmaIshlarRouteImport } from './routes/admin.yozma-ishlar'
import { Route as MilliySertifikatIndexRouteImport } from './routes/milliy-sertifikat.index'
import { Route as MilliySertifikatSubjectIdRouteImport } from './routes/milliy-sertifikat.$subjectId'
import { Route as QollanmalarIndexRouteImport } from './routes/qollanmalar.index'
import { Route as QollanmalarSlugRouteImport } from './routes/qollanmalar.$slug'
import { Route as SavollarBankiIndexRouteImport } from './routes/savollar-banki.index'
import { Route as SavollarBankiMashqRouteImport } from './routes/savollar-banki.mashq'
import { Route as ImtihonSubjectIdExamIdRouteImport } from './routes/imtihon.$subjectId.$examId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DtmRoute = DtmRouteImport.update({
  id: '/dtm',
  path: '/dtm',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriallarRoute = MateriallarRouteImport.update({
  id: '/materiallar',
  path: '/materiallar',
  getParentRoute: () => rootRouteImport,
} as any)
const NatijalarRoute = NatijalarRouteImport.update({
  id: '/natijalar',
  path: '/natijalar',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyPlanRoute = StudyPlanRouteImport.update({
  id: '/study-plan',
  path: '/study-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const TestlarRoute = TestlarRouteImport.update({
  id: '/testlar',
  path: '/testlar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminYozmaIshlarRoute = AdminYozmaIshlarRouteImport.update({
  id: '/yozma-ishlar',
  path: '/yozma-ishlar',
  getParentRoute: () => AdminRoute,
} as any)
const MilliySertifikatIndexRoute = MilliySertifikatIndexRouteImport.update({
  id: '/milliy-sertifikat/',
  path: '/milliy-sertifikat/',
  getParentRoute: () => rootRouteImport,
} as any)
const MilliySertifikatSubjectIdRoute =
  MilliySertifikatSubjectIdRouteImport.update({
    id: '/milliy-sertifikat/$subjectId',
    path: '/milliy-sertifikat/$subjectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const QollanmalarIndexRoute = QollanmalarIndexRouteImport.update({
  id: '/qollanmalar/',
  path: '/qollanmalar/',
  getParentRoute: () => rootRouteImport,
} as any)
const QollanmalarSlugRoute = QollanmalarSlugRouteImport.update({
  id: '/qollanmalar/$slug',
  path: '/qollanmalar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SavollarBankiIndexRoute = SavollarBankiIndexRouteImport.update({
  id: '/savollar-banki/',
  path: '/savollar-banki/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavollarBankiMashqRoute = SavollarBankiMashqRouteImport.update({
  id: '/savollar-banki/mashq',
  path: '/savollar-banki/mashq',
  getParentRoute: () => rootRouteImport,
} as any)
const ImtihonSubjectIdExamIdRoute = ImtihonSubjectIdExamIdRouteImport.update({
  id: '/imtihon/$subjectId/$examId',
  path: '/imtihon/$subjectId/$examId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/dtm': typeof DtmRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/materiallar': typeof MateriallarRoute
  '/natijalar': typeof NatijalarRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/study-plan': typeof StudyPlanRoute
  '/testlar': typeof TestlarRoute
  '/admin/yozma-ishlar': typeof AdminYozmaIshlarRoute
  '/milliy-sertifikat/$subjectId': typeof MilliySertifikatSubjectIdRoute
  '/qollanmalar/$slug': typeof QollanmalarSlugRoute
  '/savollar-banki/mashq': typeof SavollarBankiMashqRoute
  '/milliy-sertifikat/': typeof MilliySertifikatIndexRoute
  '/qollanmalar/': typeof QollanmalarIndexRoute
  '/savollar-banki/': typeof SavollarBankiIndexRoute
  '/imtihon/$subjectId/$examId': typeof ImtihonSubjectIdExamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/dtm': typeof DtmRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/materiallar': typeof MateriallarRoute
  '/natijalar': typeof NatijalarRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/study-plan': typeof StudyPlanRoute
  '/testlar': typeof TestlarRoute
  '/admin/yozma-ishlar': typeof AdminYozmaIshlarRoute
  '/milliy-sertifikat/$subjectId': typeof MilliySertifikatSubjectIdRoute
  '/qollanmalar/$slug': typeof QollanmalarSlugRoute
  '/savollar-banki/mashq': typeof SavollarBankiMashqRoute
  '/milliy-sertifikat': typeof MilliySertifikatIndexRoute
  '/qollanmalar': typeof QollanmalarIndexRoute
  '/savollar-banki': typeof SavollarBankiIndexRoute
  '/imtihon/$subjectId/$examId': typeof ImtihonSubjectIdExamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/dtm': typeof DtmRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/history': typeof HistoryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/materiallar': typeof MateriallarRoute
  '/natijalar': typeof NatijalarRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/study-plan': typeof StudyPlanRoute
  '/testlar': typeof TestlarRoute
  '/admin/yozma-ishlar': typeof AdminYozmaIshlarRoute
  '/milliy-sertifikat/$subjectId': typeof MilliySertifikatSubjectIdRoute
  '/qollanmalar/$slug': typeof QollanmalarSlugRoute
  '/savollar-banki/mashq': typeof SavollarBankiMashqRoute
  '/milliy-sertifikat/': typeof MilliySertifikatIndexRoute
  '/qollanmalar/': typeof QollanmalarIndexRoute
  '/savollar-banki/': typeof SavollarBankiIndexRoute
  '/imtihon/$subjectId/$examId': typeof ImtihonSubjectIdExamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/admin'
    | '/dashboard'
    | '/dtm'
    | '/forgot-password'
    | '/history'
    | '/leaderboard'
    | '/login'
    | '/materiallar'
    | '/natijalar'
    | '/onboarding'
    | '/signup'
    | '/study-plan'
    | '/testlar'
    | '/admin/yozma-ishlar'
    | '/milliy-sertifikat/$subjectId'
    | '/qollanmalar/$slug'
    | '/savollar-banki/mashq'
    | '/milliy-sertifikat/'
    | '/qollanmalar/'
    | '/savollar-banki/'
    | '/imtihon/$subjectId/$examId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/admin'
    | '/dashboard'
    | '/dtm'
    | '/forgot-password'
    | '/history'
    | '/leaderboard'
    | '/login'
    | '/materiallar'
    | '/natijalar'
    | '/onboarding'
    | '/signup'
    | '/study-plan'
    | '/testlar'
    | '/admin/yozma-ishlar'
    | '/milliy-sertifikat/$subjectId'
    | '/qollanmalar/$slug'
    | '/savollar-banki/mashq'
    | '/milliy-sertifikat'
    | '/qollanmalar'
    | '/savollar-banki'
    | '/imtihon/$subjectId/$examId'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/admin'
    | '/dashboard'
    | '/dtm'
    | '/forgot-password'
    | '/history'
    | '/leaderboard'
    | '/login'
    | '/materiallar'
    | '/natijalar'
    | '/onboarding'
    | '/signup'
    | '/study-plan'
    | '/testlar'
    | '/admin/yozma-ishlar'
    | '/milliy-sertifikat/$subjectId'
    | '/qollanmalar/$slug'
    | '/savollar-banki/mashq'
    | '/milliy-sertifikat/'
    | '/qollanmalar/'
    | '/savollar-banki/'
    | '/imtihon/$subjectId/$examId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DtmRoute: typeof DtmRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoryRoute: typeof HistoryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MateriallarRoute: typeof MateriallarRoute
  NatijalarRoute: typeof NatijalarRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  StudyPlanRoute: typeof StudyPlanRoute
  TestlarRoute: typeof TestlarRoute
  MilliySertifikatSubjectIdRoute: typeof MilliySertifikatSubjectIdRoute
  QollanmalarSlugRoute: typeof QollanmalarSlugRoute
  SavollarBankiMashqRoute: typeof SavollarBankiMashqRoute
  MilliySertifikatIndexRoute: typeof MilliySertifikatIndexRoute
  QollanmalarIndexRoute: typeof QollanmalarIndexRoute
  SavollarBankiIndexRoute: typeof SavollarBankiIndexRoute
  ImtihonSubjectIdExamIdRoute: typeof ImtihonSubjectIdExamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dtm': {
      id: '/dtm'
      path: '/dtm'
      fullPath: '/dtm'
      preLoaderRoute: typeof DtmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiallar': {
      id: '/materiallar'
      path: '/materiallar'
      fullPath: '/materiallar'
      preLoaderRoute: typeof MateriallarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/natijalar': {
      id: '/natijalar'
      path: '/natijalar'
      fullPath: '/natijalar'
      preLoaderRoute: typeof NatijalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-plan': {
      id: '/study-plan'
      path: '/study-plan'
      fullPath: '/study-plan'
      preLoaderRoute: typeof StudyPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testlar': {
      id: '/testlar'
      path: '/testlar'
      fullPath: '/testlar'
      preLoaderRoute: typeof TestlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/yozma-ishlar': {
      id: '/admin/yozma-ishlar'
      path: '/yozma-ishlar'
      fullPath: '/admin/yozma-ishlar'
      preLoaderRoute: typeof AdminYozmaIshlarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/milliy-sertifikat/': {
      id: '/milliy-sertifikat/'
      path: '/milliy-sertifikat'
      fullPath: '/milliy-sertifikat/'
      preLoaderRoute: typeof MilliySertifikatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milliy-sertifikat/$subjectId': {
      id: '/milliy-sertifikat/$subjectId'
      path: '/milliy-sertifikat/$subjectId'
      fullPath: '/milliy-sertifikat/$subjectId'
      preLoaderRoute: typeof MilliySertifikatSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qollanmalar/': {
      id: '/qollanmalar/'
      path: '/qollanmalar'
      fullPath: '/qollanmalar/'
      preLoaderRoute: typeof QollanmalarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qollanmalar/$slug': {
      id: '/qollanmalar/$slug'
      path: '/qollanmalar/$slug'
      fullPath: '/qollanmalar/$slug'
      preLoaderRoute: typeof QollanmalarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savollar-banki/': {
      id: '/savollar-banki/'
      path: '/savollar-banki'
      fullPath: '/savollar-banki/'
      preLoaderRoute: typeof SavollarBankiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savollar-banki/mashq': {
      id: '/savollar-banki/mashq'
      path: '/savollar-banki/mashq'
      fullPath: '/savollar-banki/mashq'
      preLoaderRoute: typeof SavollarBankiMashqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imtihon/$subjectId/$examId': {
      id: '/imtihon/$subjectId/$examId'
      path: '/imtihon/$subjectId/$examId'
      fullPath: '/imtihon/$subjectId/$examId'
      preLoaderRoute: typeof ImtihonSubjectIdExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminYozmaIshlarRoute: typeof AdminYozmaIshlarRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminYozmaIshlarRoute: AdminYozmaIshlarRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DtmRoute: DtmRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoryRoute: HistoryRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MateriallarRoute: MateriallarRoute,
  NatijalarRoute: NatijalarRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  StudyPlanRoute: StudyPlanRoute,
  TestlarRoute: TestlarRoute,
  MilliySertifikatSubjectIdRoute: MilliySertifikatSubjectIdRoute,
  QollanmalarSlugRoute: QollanmalarSlugRoute,
  SavollarBankiMashqRoute: SavollarBankiMashqRoute,
  MilliySertifikatIndexRoute: MilliySertifikatIndexRoute,
  QollanmalarIndexRoute: QollanmalarIndexRoute,
  SavollarBankiIndexRoute: SavollarBankiIndexRoute,
  ImtihonSubjectIdExamIdRoute: ImtihonSubjectIdExamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
