/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MilliySertifikatRouteImport } from './routes/milliy-sertifikat'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DtmRouteImport } from './routes/dtm'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MilliySertifikatSubjectIdRouteImport } from './routes/milliy-sertifikat.$subjectId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MilliySertifikatRoute = MilliySertifikatRouteImport.update({
  id: '/milliy-sertifikat',
  path: '/milliy-sertifikat',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DtmRoute = DtmRouteImport.update({
  id: '/dtm',
  path: '/dtm',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MilliySertifikatSubjectIdRoute =
  MilliySertifikatSubjectIdRouteImport.update({
    id: '/$subjectId',
    path: '/$subjectId',
    getParentRoute: () => MilliySertifikatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/dtm': typeof DtmRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/milliy-sertifikat': typeof MilliySertifikatRouteWithChildren
  '/signup': typeof SignupRoute
  '/milliy-sertifikat/$subjectId': typeof MilliySertifikatSubjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/dtm': typeof DtmRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/milliy-sertifikat': typeof MilliySertifikatRouteWithChildren
  '/signup': typeof SignupRoute
  '/milliy-sertifikat/$subjectId': typeof MilliySertifikatSubjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/dtm': typeof DtmRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/milliy-sertifikat': typeof MilliySertifikatRouteWithChildren
  '/signup': typeof SignupRoute
  '/milliy-sertifikat/$subjectId': typeof MilliySertifikatSubjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/admin'
    | '/dashboard'
    | '/dtm'
    | '/forgot-password'
    | '/leaderboard'
    | '/login'
    | '/milliy-sertifikat'
    | '/signup'
    | '/milliy-sertifikat/$subjectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/admin'
    | '/dashboard'
    | '/dtm'
    | '/forgot-password'
    | '/leaderboard'
    | '/login'
    | '/milliy-sertifikat'
    | '/signup'
    | '/milliy-sertifikat/$subjectId'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/admin'
    | '/dashboard'
    | '/dtm'
    | '/forgot-password'
    | '/leaderboard'
    | '/login'
    | '/milliy-sertifikat'
    | '/signup'
    | '/milliy-sertifikat/$subjectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  DtmRoute: typeof DtmRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MilliySertifikatRoute: typeof MilliySertifikatRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milliy-sertifikat': {
      id: '/milliy-sertifikat'
      path: '/milliy-sertifikat'
      fullPath: '/milliy-sertifikat'
      preLoaderRoute: typeof MilliySertifikatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dtm': {
      id: '/dtm'
      path: '/dtm'
      fullPath: '/dtm'
      preLoaderRoute: typeof DtmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milliy-sertifikat/$subjectId': {
      id: '/milliy-sertifikat/$subjectId'
      path: '/$subjectId'
      fullPath: '/milliy-sertifikat/$subjectId'
      preLoaderRoute: typeof MilliySertifikatSubjectIdRouteImport
      parentRoute: typeof MilliySertifikatRoute
    }
  }
}

interface MilliySertifikatRouteChildren {
  MilliySertifikatSubjectIdRoute: typeof MilliySertifikatSubjectIdRoute
}

const MilliySertifikatRouteChildren: MilliySertifikatRouteChildren = {
  MilliySertifikatSubjectIdRoute: MilliySertifikatSubjectIdRoute,
}

const MilliySertifikatRouteWithChildren =
  MilliySertifikatRoute._addFileChildren(MilliySertifikatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  DtmRoute: DtmRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MilliySertifikatRoute: MilliySertifikatRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
