/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MilliySertifikatRouteImport } from './routes/milliy-sertifikat'
import { Route as IndexRouteImport } from './routes/index'

const MilliySertifikatRoute = MilliySertifikatRouteImport.update({
  id: '/milliy-sertifikat',
  path: '/milliy-sertifikat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/milliy-sertifikat': typeof MilliySertifikatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/milliy-sertifikat': typeof MilliySertifikatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/milliy-sertifikat': typeof MilliySertifikatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/milliy-sertifikat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/milliy-sertifikat'
  id: '__root__' | '/' | '/milliy-sertifikat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MilliySertifikatRoute: typeof MilliySertifikatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/milliy-sertifikat': {
      id: '/milliy-sertifikat'
      path: '/milliy-sertifikat'
      fullPath: '/milliy-sertifikat'
      preLoaderRoute: typeof MilliySertifikatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MilliySertifikatRoute: MilliySertifikatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
